/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoalquilerdevehiculos.Vista;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectoalquilerdevehiculos.ControladorLogin.ControladorLogin;
import proyectoalquilerdevehiculos.ControladorLogin.ControladorVehiculos;
import proyectoalquilerdevehiculos.clases.AbstractVehiculo;
import proyectoalquilerdevehiculos.clases.Usuario;

/**
 *
 * @author Estudiante
 */
public class Login extends javax.swing.JFrame {
private ControladorLogin controlLogin;
    private Usuario usuarioAutenticado;
   private ControladorVehiculos listadevehiculos;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();}
    private void iniciarMenus(boolean estado) {
        MnCrearUsuario.setVisible(estado);
        mnlistau.setVisible(estado);
        vehiculos.setVisible(estado);
        MnuCoches.setVisible(estado);
        Mnumotos.setVisible(estado);
         }
    
     private void gestionarPermisosMenu() {
         
         switch (usuarioAutenticado.getTipousuario().getCodigo()){
             
             case "1":
                 iniciarMenus(true);
                 
                 
                break;
             case "2":
                 iniciarMenus(false);
                 
                 vehiculos.setVisible(true);
                 MnuCoches.setVisible(true);
                  Mnumotos.setVisible(true);
                break;
         }
}
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtContraseña = new javax.swing.JPasswordField();
        txtlogin = new javax.swing.JTextField();
        BotonIngresar = new javax.swing.JButton();
        jincoches = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCoches = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        MnCrearUsuario = new javax.swing.JMenuItem();
        mnlistau = new javax.swing.JMenuItem();
        vehiculos = new javax.swing.JMenu();
        Mnumotos = new javax.swing.JMenuItem();
        MnuCoches = new javax.swing.JMenuItem();
        mnuFurgonetas = new javax.swing.JMenuItem();
        mnucerrarsesion = new javax.swing.JMenuItem();
        mnsalir = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));

        jInternalFrame2.setTitle("Login");
        jInternalFrame2.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("*correo electronico");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("*password");

        TxtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtContraseñaActionPerformed(evt);
            }
        });

        txtlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtloginActionPerformed(evt);
            }
        });

        BotonIngresar.setText("Ingresar");
        BotonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(BotonIngresar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(txtlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                                .addComponent(TxtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(BotonIngresar)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        desktopPane.add(jInternalFrame2);
        jInternalFrame2.setBounds(1050, 60, 600, 360);

        jincoches.setClosable(true);
        jincoches.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jincoches.setIconifiable(true);
        jincoches.setMaximizable(true);
        jincoches.setResizable(true);
        jincoches.setTitle("listado de coches");
        jincoches.setVisible(false);

        tblCoches.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Extras", "Matricula", "Km", "Estado", "ValorAlquiler"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCoches);

        javax.swing.GroupLayout jincochesLayout = new javax.swing.GroupLayout(jincoches.getContentPane());
        jincoches.getContentPane().setLayout(jincochesLayout);
        jincochesLayout.setHorizontalGroup(
            jincochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jincochesLayout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        jincochesLayout.setVerticalGroup(
            jincochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jincochesLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        desktopPane.add(jincoches);
        jincoches.setBounds(30, 10, 610, 420);

        menuBar.setDoubleBuffered(true);
        menuBar.setEnabled(false);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Archivo ");
        fileMenu.setAutoscrolls(true);
        fileMenu.setEnabled(false);

        MnCrearUsuario.setMnemonic('o');
        MnCrearUsuario.setText("crear usuarios ");
        MnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCrearUsuarioActionPerformed(evt);
            }
        });
        fileMenu.add(MnCrearUsuario);

        mnlistau.setMnemonic('s');
        mnlistau.setText("lista de usuarios");
        mnlistau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnlistauActionPerformed(evt);
            }
        });
        fileMenu.add(mnlistau);

        vehiculos.setText("vehiculos");

        Mnumotos.setText("motos");
        vehiculos.add(Mnumotos);

        MnuCoches.setText("coches");
        MnuCoches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuCochesActionPerformed(evt);
            }
        });
        vehiculos.add(MnuCoches);

        mnuFurgonetas.setText("Furgonetas");
        vehiculos.add(mnuFurgonetas);

        fileMenu.add(vehiculos);

        mnucerrarsesion.setMnemonic('a');
        mnucerrarsesion.setText("cerrar sesion ");
        mnucerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnucerrarsesionActionPerformed(evt);
            }
        });
        fileMenu.add(mnucerrarsesion);

        mnsalir.setMnemonic('x');
        mnsalir.setText("salir ");
        mnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnsalirActionPerformed(evt);
            }
        });
        fileMenu.add(mnsalir);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1597, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtloginActionPerformed

    private void BotonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIngresarActionPerformed
        // TODO add your handling code here:
       if (txtlogin.getText()==null || txtlogin.getText().compareTo("")==0)
       { 
           JOptionPane.showMessageDialog(this, 
                   "Debe diligenciar el correo  ","Datos Faltantes",2);
       }
       else if(TxtContraseña.getPassword().length == 0)
       {
           JOptionPane.showMessageDialog(this, 
                   "Debe diligenciar la contraseña","Datos Faltantes",2);
           
       }
       else{
            controlLogin= new ControladorLogin();

           
            Pattern pattern = Pattern.compile("^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$");
            Matcher matcher = pattern.matcher(txtlogin.getText());//Significa que diligencio correo y contraseña
          
            
            if (matcher.find() == true) {
                usuarioAutenticado = controlLogin.
                        encontrarUsuario(txtlogin.getText(), TxtContraseña.getText());
                if (usuarioAutenticado == null) {
                    JOptionPane.showMessageDialog(this,
                            "El usuario Ingresado no existe", "Datos Erróneos", 0);
             
                } 
                else {
                
                    JOptionPane.showMessageDialog(this,
                            "Bienvenido " + usuarioAutenticado, "Bienvenido", 1);
                    gestionarPermisosMenu();
                   fileMenu.setEnabled(true);
                   jInternalFrame2.hide();
                }       
        }
           
                else {
                JOptionPane.showMessageDialog(this,
                        "El correo no tiene un formato válido", "Datos Erróneos", 0);
            }
       }
    }//GEN-LAST:event_BotonIngresarActionPerformed

    private void TxtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtContraseñaActionPerformed

    private void mnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnsalirActionPerformed

    private void mnucerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnucerrarsesionActionPerformed
        fileMenu.setEnabled(false);
        txtlogin.setText("");
        TxtContraseña.setText("");
        usuarioAutenticado = null;
        
          jInternalFrame2.show();
    }//GEN-LAST:event_mnucerrarsesionActionPerformed

    private void mnlistauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnlistauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnlistauActionPerformed

    private void MnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCrearUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnCrearUsuarioActionPerformed

     private void llenarCoches(){
         
         DefaultTableModel model = (DefaultTableModel) tblCoches.getModel();
        model.getDataVector().removeAllElements();

        for (AbstractVehiculo coches:listadevehiculos.obtenerVehiculos("coches")) {
           model.addRow(coches.obtenerArregloObjeto());
    }
        tblCoches.setModel(model);
     }
    
    private void MnuCochesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuCochesActionPerformed
jincoches.show();
        llenarCoches();
          jincoches.repaint();
        jincoches.show();
        if (jincoches.isIcon()) {
          try {
                jincoches.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }         // TODO add your handling code here:
    }//GEN-LAST:event_MnuCochesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonIngresar;
    private javax.swing.JMenuItem MnCrearUsuario;
    private javax.swing.JMenuItem MnuCoches;
    private javax.swing.JMenuItem Mnumotos;
    private javax.swing.JPasswordField TxtContraseña;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JInternalFrame jincoches;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnlistau;
    private javax.swing.JMenuItem mnsalir;
    private javax.swing.JMenuItem mnuFurgonetas;
    private javax.swing.JMenuItem mnucerrarsesion;
    private javax.swing.JTable tblCoches;
    private javax.swing.JTextField txtlogin;
    private javax.swing.JMenu vehiculos;
    // End of variables declaration//GEN-END:variables

}
